server:
  port: 8080

spring:
  application:
    name: Fanfare

  datasource:
    url: ${PSQL_URL}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#
#          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    jdbc:
      dialect: postgresql

jwt:
  secret: ${JWT_SECRET_BASE64}